version: '3.8'

services:
  # PostgreSQL Database
  postgres_db:
    image: postgres:15-alpine
    container_name: renewmart-postgres-dev
    environment:
      POSTGRES_DB: renewmart_db
      POSTGRES_USER: renewmart_user
      POSTGRES_PASSWORD: renewmart_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./renewmart/data/postgres-dev:/var/lib/postgresql/data
      - ./backend/create_tables.sql:/docker-entrypoint-initdb.d/01-create-tables.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U renewmart_user -d renewmart_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - renewmart-dev-network
    restart: unless-stopped

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: renewmart-redis-dev
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./renewmart/data/redis-dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - renewmart-dev-network
    restart: unless-stopped

  # Backend API (Development)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: renewmart-backend-dev
    environment:
      - DATABASE_URL=postgresql://renewmart_user:renewmart_password@postgres_db:5432/renewmart_db
      - REDIS_URL=redis://redis:6379/0
      - RENEWMART_REDIS_HOST=redis
      - RENEWMART_REDIS_PORT=6379
      - RENEWMART_REDIS_DB=0
      - RENEWMART_REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key-change-in-production
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - ALLOWED_ORIGINS=["http://localhost:3000", "http://localhost:5173", "http://frontend:5173"]
    volumes:
      - ./backend:/app
      - ./renewmart/uploads-dev:/app/uploads
      - ./renewmart/logs-dev:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - renewmart-dev-network
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend (Development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: renewmart-frontend-dev
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
      - VITE_API_URL=http://backend:8000/api
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - renewmart-dev-network
    restart: unless-stopped
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0"]

networks:
  renewmart-dev-network:
    driver: bridge
