version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: renewmart-postgres
    environment:
      POSTGRES_DB: renewmart_db
      POSTGRES_USER: renewmart_user
      POSTGRES_PASSWORD: renewmart_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/create_tables.sql:/docker-entrypoint-initdb.d/01-create-tables.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U renewmart_user -d renewmart_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - renewmart-network

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: renewmart-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - renewmart-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: renewmart-backend
    environment:
      - DATABASE_URL=postgresql://renewmart_user:renewmart_password@postgres:5432/renewmart_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=true
      - ALLOWED_ORIGINS=["http://localhost:3000", "http://localhost:5173", "http://frontend:5173"]
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - renewmart-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: renewmart-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - renewmart-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: renewmart-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - renewmart-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  backend_uploads:
    driver: local
  backend_logs:
    driver: local

networks:
  renewmart-network:
    driver: bridge
